export enum WavelengthGamePhases {
  WAITING = "WAITING",
  SELECTING_WORD = "SELECTING WORD",
  GUESSING_NUMBERS = "GUESSING NUMBERS",
  REVEALING = "REVEALING",
  SHOWING_LEADERBOARD = "SHOWING_LEADERBOARD",
  FINISHED = "FINISHED",
}